[aeons]
projectName = "Be Fast"

# To enable lDtk support add "ldtk-haxe-api" and "deepnightLibs". Install them using haxelib.
# To enable nape physics add "nape-haxe4". Install this using haxelib.
libraries = ["ldtk-haxe-api", "deepnightLibs"]

# To enable lDtk add "use_ldtk".
# To enable nape add "use_nape"
defines = ["use_ldtk"]

parameters = ["-dce full"]

[aeons.html5]
disableContextMenu = true
width = 960
height = 540

[[atlas]]
name = "sprites"
saveFolder = "assets"
folders = ["atlasImages/sprites"]
trimmed = true
extrude = 1
packMethod = "optimal"

[[atlas]]
name = "tiles"
saveFolder = "assets"
folders = ["atlasImages/tiles"]
trimmed = false
extrude = 1
packMethod = "basic"
noData = true
maxWidth = 340
